### ISSUE TITLE
Doesn't copy over user-defined environment variables

### ISSUE THREAD

**Issue by wamoyo** [18F/cf-blue-green#28]
From what I can tell, it doesn't copy over user-defined environment variables that might contain critical api keys, database URLs and so forth.

**Comment by dankmitchell** [comment]
Did you solve this @wamoyo?

**Comment by lauraGgit** [comment]
Yes, typically we just persist the environment variables with the `cf create-user-provider-service` command and then bind the service to the manifest.

**Comment by dankmitchell** [comment]
Thanks for the reply @lauraGgit. 

Does this look right?

`cf create-user-provided-service foobar-service-environment-variables -p '{"AWS_BUCKET":"XXX","AWS_KEY":"XXX","AWS_SECRET":"XXX","AWS_REGION":"XXX"}'`

**Comment by lauraGgit** [comment]
@danmitchell yup, although, if you're provider has s3 in its `cf marketplace`, you can just create a bucket that way and then you won't need to manually supply the aws credentials.

**Comment by dankmitchell** [comment]
Nice! We don’t have s3 yet but good to know for the future. How would I access these credentials in my app now? I.e. the out of a Jason structure so ENV[‘S3_BUCKET’] is nil...

**Comment by lauraGgit** [comment]
The services are in an array under the `user-provided` key in the object.

If you've bound your service to your app you can view the `VCAP_SERVICES` env var a couple of different ways. 

First, is via the `cf env APP_NAME` which will display the full envs available to the app.

Generally, you'll need to create your own parser (it does look like there is an npm module to parse though).
Here's an example of what the object for an app that has a number of bound services and the corresponding node.js parser look like:

https://github.com/18F/fs-intake-module/blob/master/server/vcap-constants.es6
https://github.com/18F/fs-intake-module/tree/master/server#environment-variables

**Comment by stvnrlly** [comment]
For parsing `VCAP_SERVICES` out of the environment variables, there are good options for Python, Ruby, and Node.

- Python: https://pypi.python.org/pypi/cfenv
- Ruby: https://github.com/bkeepers/dotenv (not cloud foundry specific, but it'll work)
- Node: https://www.npmjs.com/package/cfenv

You can also create user-provided services from a file, as shown in https://github.com/18F/calc/blob/develop/docs/deploy.md#services. As they mention, that file should be treated like most `.env` files and kept secret. That might incentivize one big service over individual services for each component; we seem to prefer the latter for easier editing down the line.

**Comment by dankmitchell** [comment]
Thanks @lauraGgit !

Thanks @stvnrlly, i've come across this gem which looks like the same thing https://github.com/cloudfoundry/cf-app-utils-ruby 👍

**Comment by wamoyo** [comment]
@danmitchell- I never did. I eventually moved on to other architectures and other providers.
